apiVersion: v1
kind: Pod
metadata:
  name: namegenerator
spec:
  containers:
    - name: namegenerator
      command: ['python','name_generator.py']
      image: arimatch1/pyproject1-name-generator:project1.v4
      tty: true
      stdin: true
  imagePullSecrets:
    - name: myregistrykey
